language: node_js
# sudo: required
node_js:
  - 11.0.0
cache:
  directories:
    - node_modules
script:
    - npm run build
    - git add -A
    - git commit -m 'deploy'
    - git push -f git@github.com:xiaotianxia/xiaotianxia.github.io.git master
branch: master